### ISSUE TITLE
A proper health check for containerized prerender

### ISSUE THREAD

**Issue by ZitRos** [prerender/prerender#650]
Hello! Thanks for a great project.

I was wondering what's the best way to do a health check for [containerized prerender](https://hub.docker.com/r/zitros/prerender).

Currently, I did it in a bit weird way (it requests `www.google.com`):

```
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 120
  httpGet:
    path: /render?url=https%3A%2F%2Fwww.google.com
    port: 80
```

But what I want ultimately is to request a dummy light local endpoint. Ideally, have a path like `/healthz` served by prerender, which will under the hood query local `/render?url=localhost...` and verify the rendering engine works. I can make a PR here as well.

What do you think?
